### ISSUE TITLE
How to prepare the roundXbarcodes file？

### ISSUE THREAD

**Issue by AlicePsyche** [paulranum11/SPLiT-Seq_demultiplexing#3]
Hi, Paul

Thank you very much for developing this useful tool! I am new to the SPLiT-seq data analysis, just want to make sure how could I prepare the  roundXbarcode files from my primer list. Below are my 1st round primers that I used in experiments.

``` 1st round primers
AGGTCAGAGCATTGAAACATCGTTTTTTTTTTTTTTTVN
AGGTCAGAGCATTGATGCCTAATTTTTTTTTTTTTTTVN
AGGTCAGAGCATTGAGTGGTCATTTTTTTTTTTTTTTVN
AGGTCAGAGCATTGATCATTCCNNNNNN	
AGGTCAGAGCATTGATTGGCTCNNNNNN	
AGGTCAGAGCATTGCAAGGAGCNNNNNN
```

So the corresponding file should be:
```
AGGTCAGAGCATTGAAACATCG
AGGTCAGAGCATTGATGCCTAA
AGGTCAGAGCATTGAGTGGTCA
AGGTCAGAGCATTGATCATTCC	
AGGTCAGAGCATTGATTGGCTC	
AGGTCAGAGCATTGCAAGGAGC	
``` 

It looks like your example file barcode is much shorter, could you please explain a little bit more about the file preparation? 

Thanks for your help!

Best,
Monica

**Comment by paulranum11** [comment]
Hi Monica, 

If you are using the published SPLiT-Seq oligos for rounds 1-3 then you can directly use the following example barcode files provided in the github repository.  

Round1_barcodes_new5.txt
Round2_barcodes_new4.txt
Round3_barcodes_new4.txt

However, it looks like your barcodes are distinct from the published set.  To convert the round1 oligo sequences to the sequences used for demultiplexing follow the following steps.

STEP 1: Collect your oligo sequences:
`AGGTCAGAGCATTGAAACATCGTTTTTTTTTTTTTTTVN`
`AGGTCAGAGCATTGATGCCTAATTTTTTTTTTTTTTTVN`
`AGGTCAGAGCATTGAGTGGTCATTTTTTTTTTTTTTTVN`
`AGGTCAGAGCATTGATCATTCCNNNNNN`
`AGGTCAGAGCATTGATTGGCTCNNNNNN`
`AGGTCAGAGCATTGCAAGGAGCNNNNNN`

STEP 2: Identify your unique 8bp barcode sequences:
`AAACATCG`
`ATGCCTAA`
`AGTGGTCA`
`ATCATTCC`
`ATTGGCTC`
`CAAGGAGC`

STEP 3: Add a 8bp overhang that matches the static part of the Round1 oligo: 
`GAGCATTGAAACATCG`
`GAGCATTGATGCCTAA`
`GAGCATTGAGTGGTCA`
`GAGCATTGATCATTCC`
`GAGCATTGATTGGCTC`
`GAGCATTGCAAGGAGC`

These sequences are then ready to use for demultiplexing.  


Please note... Overhangs are used to prevent a round 1 barcode from matching to a barcode 2 position in a read.  The SPLiT-Seq oligos reuse the same 96 8bp unique barcodes in the round 1-3 oligos. A range of overhang sizes were evaluated but 8bp was chosen for Round1 because it facilitates a higher number of mismatches without allowing barcode collisions.  

I hope this helps,
- Paul

**Comment by AlicePsyche** [comment]
OH! Thank you very much for your prompt reply, now I totally understand. 

Thanks again!
